### PR TITLE
0x611c74310a06b10593e073affe4ea543b793f539

### PR DESCRIPTION
**Pull request by fincrypchain-io**
https://etherscan.io/address/0x611c74310a06b10593e073affe4ea543b793f539
Fincrypchain  (FCC)

### CODE REVIEW

**Comment by ceres3idoo** [comment]
What is the goal of this PR?

**Comment by fincrypchain-io** [comment]
Token Information
The Fincrypchain Token (symbol: FCC ) will be used as currency within our 
platform, and will therefore be used for donations, purchases. Using the 
Ethereum blockchain our community will be able to receive payments safely 
and quickly, thus eliminating the annoying problems and slowness of the fiat 
currencies.
Fincrypchain ( FCC ) token is a long term project, all our calculations have been 
made in order to guarantee an
“uninterrupted” production flow, (all this regardless of the various market 
fluctuations). Our token will be essential for:
• Making a donation
• Purchasing a song 
• Royalty Payouts
It will be used as means of payment on the cryptology research system.

**Comment by ceres3idoo** [comment]
Thankyou,  but we have no time now to integrate your request.

**Comment by fincrypchain-io** [comment]
its ok sir ... take your time ... we understand as long we can work together ... thanks

**Pull request closed without merging**
